name: ESP8266 Arduino CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:

jobs:

  # Normal builds
  build-linux:
    name: Build ${{ matrix.mod }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mod: [0, 1, 2, 3, 4, 5, 6, 7]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build Sketches
      run: |
        TRAVIS_BUILD_DIR=$GITHUB_WORKSPACE BUILD_PARITY=custom mod=8 rem=${{ matrix.mod }} bash ./tests/build.sh


  # Enable IPv6 and DEBUG
  build-debug-ipv6:
    name: Debug IPv6 ${{ matrix.mod }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mod: [0, 1, 2, 3, 4, 5, 6, 7]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build Sketches
      run: |
        TRAVIS_BUILD_DIR=$GITHUB_WORKSPACE BUILD_PARITY=custom mod=8 rem=${{ matrix.mod }} bash ./tests/debug6.sh


  # Windows
  build-windows:
    name: Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build Sketches
      run: |
        copy (get-command python).source (get-command python).source.Replace("python.exe", "python3.exe")
        $env:TRAVIS_BUILD_DIR=$env:GITHUB_WORKSPACE
        $env:WINDOWS="1"
        $env:BUILD_PARITY='"custom"'
        $env:mod="500"
        $env:rem="1"
        bash ./tests/build.sh


  # Mac
  build-mac:
    name: Mac
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build Sketches
      run: |
        TRAVIS_BUILD_DIR=$GITHUB_WORKSPACE MACOSX=1 BUILD_PARITY=custom mod=500 rem=1 bash ./tests/build.sh


  # Platform.IO quick builds
  build-pio:
    name: Build Platform.IO
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build subset on Platform.IO
      run: |
        sudo apt-get install python3-pip python3-setuptools
        PATH=/home/runner/.local/bin:$PATH TRAVIS_BUILD_DIR=$GITHUB_WORKSPACE BUILD_PARITY=custom mod=27 rem=8 bash ./tests/platformio.sh


  host-tests:
    name: Host tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run host tests
      run: |
        sudo apt-get install valgrind lcov
        TRAVIS_BUILD_DIR=$GITHUB_WORKSPACE bash ./tests/ci/host_test.sh


  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build documentation
      run: |
        sudo apt-get install python3-pip python3-setuptools
        PATH=/home/runner/.local/bin:$PATH pip3 install --user -r doc/requirements.txt
        PATH=/home/runner/.local/bin:$PATH TRAVIS_BUILD_DIR=$GITHUB_WORKSPACE ./tests/ci/build_docs.sh


  style-check:
    name: Style and formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Style check
      run: |
          TRAVIS_BUILD_DIR=$GITHUB_WORKSPACE sudo ./tests/ci/install_astyle.sh
          PATH=/home/runner/bin:$PATH TRAVIS_BUILD_DIR=$GITHUB_WORKSPACE ./tests/ci/style_check.sh


  mock-check:
    name: Mock trivial test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Mock build
      run: |
          TRAVIS_BUILD_DIR=$GITHUB_WORKSPACE ./tests/buildm.sh


  boards-check:
    name: Boards.txt check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Boards.txt diff
      run: |
          TRAVIS_BUILD_DIR=$GITHUB_WORKSPACE ./tests/ci/build_boards.sh