# Whenever a release is published from a draft, this will update the
# master Arduino JSON file to add its new entry.

name: ESP8266 Arduino Release Publisher

on:
  release:
    types: [published]

jobs:
  package:
    name: Update master JSON file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set GIT tag name
      run: |
        echo "::set-env name=TRAVIS_TAG::$(git describe --exact-match --tags)"
    - name: Deploy updated JSON
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
        BUILD_TYPE: package
        GHKEY: ${{ secrets.GHKEY }}
        GHIV: ${{ secrets.GHIV }}
      run: |
           bash ./tests/ci/build_package.sh
           # Only the regenerated JSON file will be used, but it's simpler than looking for it in a GH release
           bash ./package/deploy_package_index.sh