# Whenever a release is published from a draft, this will update the
# global JSON file to add its new entry.

name: ESP8266 Arduino Release Publisher

on:
  release:
    types: [published]

jobs:
  package:
    name: Update global JSON file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build package JSON
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
        BUILD_TYPE: package
        GHKEY: ${{ secrets.GHKEY }}
        GHIV: ${{ secrets.GHIV }}
      run: |
           bash bash package/deploy_package_index.sh