name: ESP8266 Arduino Tag to Release

on:
  push:
    tags:

jobs:

  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build package JSON
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
        BUILD_TYPE: package
        CI_GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        TRAVIS_TAG: ${{ github.ref }}
      run: |
           bash ./tests/ci/build_package.sh
    - name: Create release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: true
        prerelease: true
    - name: Upload ZIP file
      id: upload-release-asset-zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: package/versions/${{ github.ref }}/esp8266-${{ github.ref }}.zip
        asset_name: esp8266-${{ github.ref }}.zip
        asset_content_type: application/zip
    - name: Upload JSON
      id: upload-release-asset-json
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: package/versions/${{ github.ref }}/package_esp8266com_index.json
        asset_name: package_esp8266com_index.json
        asset_content_type: application/json
